Fatal error: exception Failure("Function with name testvar and given
    argument types exists")
